// vue-vuex-typescript/src/views/Login.vue
<template>
  <div class="passport-panel">
    <h3>登录</h3>
    <a-input
      size="large"
      v-model="loginForm.username"
      placeholder="请输入用户名"/>
    <a-input 
      size="large"
      type="password"
      v-model="loginForm.password"
      placeholder="请输入密码"/>
    <a-button 
      type="primary"
      @click="() => handleLogin(loginForm)"
      size="large">登录</a-button>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { Button, Input } from 'ant-design-vue';
import { State, Action } from 'vuex-class';
import { LoginForm } from '@/stores/state';

@Component({
  components: {
    [Button.name]: Button,
    [Input.name]: Input
  }
})
export default class extends Vue {
  @State private loginForm?: LoginForm;
  @State private ableSubmit!: boolean;

  @Action private handleLogin!: (loginForm: LoginForm) => void;
}

</script>

<style lang="scss">
@import '@/styles/passport.scss';
</style>

// react-redux-saga-spa/src/pages/Login.js
import React, { Component } from 'react';
import { connect } from 'react-redux';

import '../styles/passport.scss';

import * as _ from '../utils/tool';

import { Button, Input } from 'antd';

@connect(
  state => ({
    login: state.login
  })
)
export default class extends Component {

  // 表单修改
  handleChange = (type, e) => this.props.dispatch({
    type: 'changeForm',
    payload: {
      [type]: e.target.value
    }
  });

  // 提交
  handleSubmit = () => this.props.dispatch({
    type: 'handleLogin',
    history: this.props.history
  })

  render() {
    let { login } = this.props;
    let { loginForm, ableSubmit } = login;
    
    return (
      <div className="passport-panel">
        <h3>登录</h3>
        <Input
          size="large"
          value={loginForm.username}
          onChange={this.handleChange.bind(null, 'username')}
          placeholder="请输入用户名"/>
        <Input 
          size="large"
          value={loginForm.password}
          onChange={this.handleChange.bind(null, 'password')}
          type="password"
          placeholder="请输入密码"/>
        <Button 
          onClick={this.handleSubmit}
          loading={!ableSubmit}
          type="primary"
          size="large">登录</Button>
      </div>
    )
  }
}
