// vue-vuex-spa/src/views/Login.vue
<template>
  <div class="passport-panel">
    <h3>登录</h3>
    <a-input
      size="large"
      v-model="loginForm.username"
      placeholder="请输入用户名"/>
    <a-input 
      size="large"
      type="password"
      v-model="loginForm.password"
      placeholder="请输入密码"/>
    <a-button 
      type="primary"
      :loading="!ableSubmit"
      @click="() => handleLogin(loginForm)"
      size="large">登录</a-button>
  </div>
</template>

<script>
import { Component, Vue } from 'vue-property-decorator';
import { Button, Input } from 'ant-design-vue';
import { State, Action, namespace } from 'vuex-class';

const login = namespace('login');

@Component({
  components: {
    [Button.name]: Button,
    [Input.name]: Input
  }
})
export default class Login extends Vue {
  @login.State loginForm;
  @login.State ableSubmit;

  @login.Action handleLogin;
}

</script>

<style lang="scss">
@import '@/styles/passport.scss';
</style>

// react-redux-thunk-spa/src/pages/Login.js
import React, { Component } from 'react';
import { connect } from 'react-redux';

import '../styles/passport.scss';

import * as _ from '../utils/tool';

import { Button, Input } from 'antd';
import { changeForm, handleLogin } from '../stores/actions';
import { updateUser } from '../stores/actions/app';

@connect(
  state => ({
    login: state.login,
    redirect: state.app.redirect
  }),
  { changeForm, handleLogin, updateUser }
)
export default class extends Component {

  // 表单修改
  handleChange = (type, e) => this.props.changeForm({ [type]: e.target.value});

  // 提交
  handleSubmit = () => this.props.handleLogin(this.props.login.loginForm).then(d => {
    if(d) {
      this.props.history.replace(this.props.redirect)
      this.props.updateUser(d);
    }
  });

  render() {

    let { login } = this.props;
    let { loginForm, ableSubmit } = login;
    
    return (
      <div className="passport-panel">
        <h3>登录</h3>
        <Input
          size="large"
          value={loginForm.username}
          onChange={this.handleChange.bind(null, 'username')}
          placeholder="请输入用户名"/>
        <Input 
          size="large"
          value={loginForm.password}
          onChange={this.handleChange.bind(null, 'password')}
          type="password"
          placeholder="请输入密码"/>
        <Button 
          onClick={this.handleSubmit}
          loading={!ableSubmit}
          type="primary"
          size="large">登录</Button>
      </div>
    )
  }
}
